### PR TITLE
Michael Branch

### PR DESCRIPTION
**Pull request by MichaelFellas**
Created Branch for Michael

### CODE REVIEW

**Review by MichaelFellas — COMMENTED** [review]
Merged all javascript, shouldn't have broken anything

**Review by MichaelFellas — COMMENTED** [review]
Added Checklist and Title Mock up

**Review by MichaelFellas — COMMENTED** [review]
Deny this one I think it will fuck it up

**Review by HannahAB777 — APPROVED** [review]
thanks for this looks great

**Pull request merged**
